[package]
name = "wasm-sim"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
smallvec = "1"
ahash = { version = "0.8", default-features = false, features = ["std", "compile-time-rng"] }
